### ISSUE TITLE
Theme Check info bzgl. require_once

### ISSUE THREAD

**Issue by CoachBirgit** [inpsyde/helsinki#6]
> INFO: customizer.php The theme appears to use include or require. If these are being used to include separate sections of a template from independent files, then get_template_part() should be used instead.
> Line 125: require_once ( ABSPATH . '/wp-admin/includes/file.php' );

s. https://github.com/inpsyde/helsinki/blob/master/application/customizer.php#L125

**Comment by dasllama** [comment]
Richtig, das kann ich aber nicht fixen, weil ich hier wirklich den require_once brauche.
